/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type deMessage from '../locales/de/messages.json';
import type enMessage from '../locales/en/messages.json';
import type esMessage from '../locales/es/messages.json';
import type frMessage from '../locales/fr/messages.json';
import type jaMessage from '../locales/ja/messages.json';
import type koMessage from '../locales/ko/messages.json';
import type ruMessage from '../locales/ru/messages.json';
import type zh_CNMessage from '../locales/zh_CN/messages.json';

export type MessageKey = keyof typeof deMessage &
  keyof typeof enMessage &
  keyof typeof esMessage &
  keyof typeof frMessage &
  keyof typeof jaMessage &
  keyof typeof koMessage &
  keyof typeof ruMessage &
  keyof typeof zh_CNMessage;

export type DevLocale = 'de' | 'en' | 'es' | 'fr' | 'ja' | 'ko' | 'ru' | 'zh_CN';
